### ISSUE TITLE
Error: chat_data is not a string 

### ISSUE THREAD

**Issue by AchuAshwath** [Alfex4936/Bard-rs#10]
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\Users\Admin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\bard-rs-1.2.1\src\main.rs:521:68 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by 7Moses** [comment]
Here is my attempt at updating and it did not work out, 

 ~/xxxxx/Bard-rs (drafting●)$ cargo install bard-rs

Compiling bard-rs v1.2.2 

    Finished release [optimized] target(s) in 10m 25s

   Replacing /Users/xxxxx/.cargo/bin/bard-rs

    Replaced package `bard-rs v1.2.1` with `bard-rs v1.2.2` (executable `bard-rs`)

Then tried this 

~/xxxxx/Bard-rs (drafting)$ bard-rs -e .env -p ./

thread 'main' panicked at 'SNlM0e not found', /Users/xxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bard-rs-1.2.2/src/main.rs:134:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

~/xxxxx/Bard-rs (drafting)$  

Any updates welcome,

**Comment by Alfex4936** [comment]
Can you check with the latest version?

`cargo install bard-rs -f`

**Comment by davidcortesortuno** [comment]
I updated to the latest version and I found:

```
Error: chat_data is not a string
thread 'main' panicked at /home/xxxxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bard-rs-1.2.5/src/main.rs:525:68:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by webbrain-one** [comment]
Thanks for catching this! I’ve just opened a PR to fix it: https://github.com/Alfex4936/Bard-rs/pull/16. The panic was caused by calling `.unwrap()` on a `None` value when `chat_data` wasn't properly returned or parsed as a string. This PR adds safer validation and error handling to prevent the crash. Let me know if you'd like to test it out or have any questions. Thanks again for the report! 🙌
